Repository venus-lion/movlit, pull requests merged in 2025-01, with the labels that each got.

#44 [be] Security 경로 추가
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
Labels: For: Api, Type: Fix

#47 [be,fe] 영화 상세 페이지 장르 조회 API 및 테스트 코드, 페이지 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/util/Genre.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieCrewRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieGenreRepository.java
  be/src/main/java/movlit/be/movie/infra/MovieRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieGenreRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieGenreJpaRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailReadController.java
  be/src/main/java/movlit/be/movie/presentation/MovieMainController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieDetailGenreResponse.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieListByGenreResponseDto.java
  be/src/main/resources/application-db-local.yml
  be/src/test/java/movlit/be/acceptance/AcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie/MovieDetailAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie/MovieDetailSteps.java
  be/src/test/resources/data.sql
  fe/src/components/MovieDetailPage.jsx
Labels: For: Api, For: View, Type: Feature

#50 Fix(be) #39 : elasticsearch index setting, mapping
  be/src/main/java/movlit/be/movie/domain/document/MovieDocument.java
  be/src/main/java/movlit/be/movie/domain/document/MovieGenreForDocument.java
  be/src/main/java/movlit/be/movie/domain/document/MovieTagForDocument.java
  be/src/main/resources/mappings/movie-mapping.json
  be/src/main/resources/mappings/movie-setting.json
Labels: For: Api, Type: Fix

#52 [be, fe] 영화 코멘트 API, 페이지 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/MemberAndMovieCommentNotMatchedException.java
  be/src/main/java/movlit/be/common/exception/MovieCommentNotFound.java
  be/src/main/java/movlit/be/movie/application/converter/detail/MovieConvertor.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailWriteService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieCommentRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieCommentRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieCommentJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailReadController.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailWriteController.java
  be/src/main/java/movlit/be/movie/presentation/dto/request/MovieCommentDataForDelete.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCommentReadResponse.java
  be/src/test/java/movlit/be/acceptance/movie_comment/MovieCommentAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie_comment/MovieCommentSteps.java
  fe/src/components/MovieDetailPage.jsx
Labels: For: Api, For: View, Type: Feature, Type: Fix

#56 [be, fe] 생년월일 방식, 코멘트 API + 페이징 구현 완료
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/MemberExistsInMovieCommentException.java
  be/src/main/java/movlit/be/movie/application/converter/detail/MovieConvertor.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailWriteService.java
  be/src/main/java/movlit/be/movie/domain/entity/MovieCommentEntity.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieCommentRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieCommentRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieCommentJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailReadController.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailWriteController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieMyCommentReadResponse.java
  be/src/test/java/movlit/be/acceptance/movie_comment/MovieCommentAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie_comment/MovieCommentSteps.java
  fe/package-lock.json
  fe/package.json
  fe/src/components/MovieDetailPage.jsx
  fe/src/pages/MemberRegister.jsx
Labels: For: Api, For: View, Type: Feature, Type: Fix

#58 Fix(be) #49: 사용자 취향 장르 가져오는 API 진행중
  be/src/main/java/movlit/be/common/config/ElasticSearchConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/MemberGenreNotFoundException.java
  be/src/main/java/movlit/be/common/util/ids/MovieHeartId.java
  be/src/main/java/movlit/be/member/domain/MemberGenre.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenreEntity.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenreIdEntity.java
  be/src/main/java/movlit/be/member/domain/repository/MemberRepository.java
  be/src/main/java/movlit/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberGenreJpaRepository.java
  be/src/main/java/movlit/be/movie/application/converter/main/MovieConverter.java
  be/src/main/java/movlit/be/movie/application/converter/main/MovieGenreConverter.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainService.java
  be/src/main/java/movlit/be/movie/domain/Movie.java
  be/src/main/java/movlit/be/movie/domain/MovieGenre.java
  be/src/main/java/movlit/be/movie/domain/entity/MovieEntity.java
  be/src/main/java/movlit/be/movie/domain/entity/MovieGenreEntity.java
  be/src/main/java/movlit/be/movie/domain/entity/MovieHeartEntity.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieSearchRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieMainController.java
  fe/src/pages/MovieHome.jsx
Labels: For: Api, For: View, Type: Feature, Type: Refactor

#62 [be, fe] 영화 코멘트 좋아요 API, 페이지 구현
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/MovieCommentLikeAlreadyExistsException.java
  be/src/main/java/movlit/be/common/exception/MovieCommentLikeNotFoundException.java
  be/src/main/java/movlit/be/common/util/IdFactory.java
  be/src/main/java/movlit/be/common/util/ids/MovieCommentLikeCountId.java
  be/src/main/java/movlit/be/common/util/ids/MovieCommentLikeId.java
  be/src/main/java/movlit/be/movie/application/converter/detail/MovieConvertor.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailWriteService.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieCommentJpaRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieDetailJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCommentReadResponse.java
  be/src/main/java/movlit/be/movie_comment_heart/application/service/MovieCommentLikeService.java
  be/src/main/java/movlit/be/movie_comment_heart/domain/entity/MovieCommentLikeEntity.java
  be/src/main/java/movlit/be/movie_comment_heart/domain/repository/MovieCommentLikeRepository.java
  be/src/main/java/movlit/be/movie_comment_heart/infra/MovieCommentLikeRepositoryImpl.java
  be/src/main/java/movlit/be/movie_comment_heart/infra/persistence/MovieCommentLikeJpaRepository.java
  be/src/main/java/movlit/be/movie_comment_heart/presentation/MovieCommentLikeController.java
  be/src/main/java/movlit/be/movie_comment_heart/presentation/dto/response/MovieCommentLikeResponse.java
  be/src/main/java/movlit/be/movie_comment_heart_count/application/service/MovieCommentLikeCountService.java
  be/src/main/java/movlit/be/movie_comment_heart_count/domain/MovieCommentLikeCountRepository.java
  be/src/main/java/movlit/be/movie_comment_heart_count/domain/entity/MovieCommentLikeCountEntity.java
  be/src/main/java/movlit/be/movie_comment_heart_count/infra/persistence/MovieCommentLikeCountRepositoryImpl.java
  be/src/main/java/movlit/be/movie_comment_heart_count/infra/persistence/jpa/MovieCommentLikeCountJpaRepository.java
  fe/package-lock.json
  fe/package.json
  fe/src/components/MovieDetailPage.jsx
Labels: For: Api, For: View, Type: Fix

#63 [be, fe] 장르 조회 API + 페이지 / 멤버 장르 조회 API 구현
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/util/Genre.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberReadService.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  be/src/main/java/movlit/be/member/domain/Member.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenreEntity.java
  be/src/main/java/movlit/be/member/domain/repository/MemberGenreRepository.java
  be/src/main/java/movlit/be/member/domain/repository/MemberRepository.java
  be/src/main/java/movlit/be/member/infra/persistence/MemberGenreRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberGenreJpaRepository.java
  be/src/main/java/movlit/be/member/presentation/MemberController.java
  be/src/main/java/movlit/be/member/presentation/dto/request/MemberRegisterRequest.java
  be/src/main/java/movlit/be/member/presentation/dto/response/GenreListReadResponse.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainService.java
  be/src/test/java/movlit/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/member/MemberSteps.java
  be/src/test/java/movlit/be/acceptance/util/MemberFixture.java
  be/src/test/resources/data.sql
  fe/package-lock.json
  fe/package.json
  fe/src/pages/MemberRegister.jsx
Labels: For: Api, For: View, Type: Feature

#65 [fe] 마이페이지 구현
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberReadService.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenreEntity.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenres.java
  be/src/main/java/movlit/be/member/domain/repository/MemberRepository.java
  be/src/main/java/movlit/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/java/movlit/be/member/presentation/MemberController.java
  be/src/main/java/movlit/be/member/presentation/dto/request/MemberUpdateRequest.java
  be/src/main/java/movlit/be/member/presentation/dto/response/MemberReadMyPage.java
  be/src/main/java/movlit/be/member/presentation/dto/response/MemberUpdateResponse.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieJpaRepository.java
  be/src/test/java/movlit/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/member/MemberSteps.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.jsx
  fe/src/components/MyPage.css
  fe/src/components/MyPage.jsx
  fe/src/main.jsx
Labels: For: View, Type: Feature

#69 [be] Hot fix (OAuth 부분 구현 추가)
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/common/filter/JwtRequestFilter.java
  be/src/main/java/movlit/be/common/util/UniqueNicknameGenerator.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  be/src/main/java/movlit/be/member/presentation/MemberController.java
  be/src/main/java/movlit/be/member/presentation/dto/request/MemberRegisterOAuth2Request.java
  be/src/main/java/movlit/be/member/presentation/dto/response/MemberRegisterOAuth2Response.java
Labels: For: Api, Type: Feature, Type: Fix

#73 [be] Oauth2 백엔드 구현
  be/src/main/java/movlit/be/auth/application/service/MyMemberDetails.java
  be/src/main/java/movlit/be/auth/application/service/MyOAuth2MemberService.java
  be/src/main/java/movlit/be/auth/application/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  fe/src/pages/MemberLogin.jsx
  fe/src/pages/MemberRegister.jsx
  fe/vite.config.js
Labels: For: Api, Type: Feature

#74 [be, fe] 회원 프로필 수정 API + 페이지 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/ElasticSearchConfig.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/member/domain/entity/MemberGenreEntity.java
  be/src/main/java/movlit/be/member/presentation/dto/request/MemberUpdateRequest.java
  be/src/test/java/movlit/be/acceptance/member/MemberSteps.java
  fe/src/components/MyPage.css
  fe/src/components/MyPage.jsx
  fe/src/main.jsx
  fe/src/pages/MemberUpdate.jsx
Labels: For: Api, For: View, Type: Feature, Type: Fix

#76 Be/feat/#68 user based recommend api
  be/src/main/java/movlit/be/member/infra/persistence/MemberGenreRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberGenreJpaRepository.java
  be/src/main/java/movlit/be/movie/application/converter/main/MovieDocumentConverter.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainService.java
  be/src/main/java/movlit/be/movie/domain/document/MovieDocument.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieSearchRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieMainController.java
  be/src/main/java/movlit/be/movie_heart/application/converter/MovieHeartConverter.java
  be/src/main/java/movlit/be/movie_heart/domain/MovieHeart.java
  be/src/main/java/movlit/be/movie_heart/domain/repository/MovieHeartRepository.java
  be/src/main/java/movlit/be/movie_heart/infra/MovieHeartRepositoryImpl.java
  be/src/main/resources/mappings/movie-mapping.json
  fe/src/hooks/useMovieList.js
  fe/src/pages/Home.css
  fe/src/pages/LatestMovies.js
  fe/src/pages/MovieCarousel.jsx
  fe/src/pages/MovieHome.css
  fe/src/pages/MovieHome.jsx
  fe/src/pages/PopularMovies.js
Labels: For: Api, For : Repository, For: View, Type: Feature

#78 Movie Main화면 에러 일시적으로 제거
  fe/package-lock.json
  fe/src/hooks/useMovieList.jsx
  fe/src/pages/LatestMovies.jsx
  fe/src/pages/MovieCarousel.jsx
  fe/src/pages/MovieHome.jsx
  fe/src/pages/PopularMovies.jsx
Labels: For: View

#77 [be, fe] 회원 탈퇴 API + 페이지 구현
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/member/application/service/MemberWriteService.java
  be/src/main/java/movlit/be/member/domain/entity/MemberEntity.java
  be/src/main/java/movlit/be/member/domain/repository/MemberRepository.java
  be/src/main/java/movlit/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/java/movlit/be/member/presentation/MemberController.java
  be/src/test/java/movlit/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/member/MemberSteps.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/components/MyPage.css
  fe/src/components/MyPage.jsx
Labels: For: Api, For: View, Type: Feature

#86 [be, fe] 이미지 업로드 API + 페이지 구현
  be/.gitignore
  be/build.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/S3Config.java
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/common/exception/ErrorMessage.java
  be/src/main/java/movlit/be/common/exception/ImageAlreadyExistsInMemberException.java
  be/src/main/java/movlit/be/common/util/IdFactory.java
  be/src/main/java/movlit/be/common/util/ids/ImageId.java
  be/src/main/java/movlit/be/image/application/service/ImageService.java
  be/src/main/java/movlit/be/image/domain/entity/ImageEntity.java
  be/src/main/java/movlit/be/image/domain/repository/ImageRepository.java
  be/src/main/java/movlit/be/image/infra/persistence/ImageRepositoryImpl.java
  be/src/main/java/movlit/be/image/infra/persistence/jpa/ImageJpaRepository.java
  be/src/main/java/movlit/be/image/presentation/ImageController.java
  be/src/main/java/movlit/be/image/presentation/dto/response/ImageResponse.java
  be/src/main/java/movlit/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/resources/application.yml
  be/src/test/java/movlit/be/acceptance/image/ImageAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/image/ImageSteps.java
  be/src/test/resources/images/potato.jpg
  fe/src/App.css
  fe/src/App.jsx
  fe/src/components/MyPage.css
  fe/src/components/MyPage.jsx
Labels: For: Api, For: View, Type: Feature

#89 [be, fe] 디테일 수정
  be/src/main/java/movlit/be/image/application/convertor/ImageConvertor.java
  be/src/main/java/movlit/be/image/application/service/ImageService.java
  be/src/main/java/movlit/be/image/application/service/S3Service.java
  be/src/main/java/movlit/be/image/domain/entity/ImageEntity.java
  be/src/main/java/movlit/be/image/domain/repository/ImageRepository.java
  be/src/main/java/movlit/be/image/infra/persistence/ImageRepositoryImpl.java
  be/src/main/java/movlit/be/image/infra/persistence/jpa/ImageJpaRepository.java
  be/src/main/java/movlit/be/image/presentation/ImageController.java
  be/src/main/java/movlit/be/member/domain/repository/MemberRepository.java
  be/src/main/java/movlit/be/movie/domain/entity/MovieCommentEntity.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieDetailJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/dto/request/MovieCommentRequest.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCommentReadResponse.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieDetailResponse.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieMyCommentReadResponse.java
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.jsx
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.jsx
  fe/src/pages/MemberLogin.jsx
  fe/src/pages/MemberRegister.jsx
Labels: For: Api, For: View, Type: Feature, Type: Fix

#96 [be, fe] 영화 상세 페이지 추천 API + 페이지 구현
  be/src/main/java/movlit/be/book/application/service/GetBooksByRandomGenreService.java
  be/src/main/java/movlit/be/book/presentation/BookMainController.java
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailSearchService.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainSearchService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieGenreRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieSearchRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieGenreRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailSearchController.java
  be/src/test/java/movlit/be/acceptance/movie/MovieDetailSearchAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie/MovieDetailSearchSteps.java
  be/src/test/java/movlit/be/acceptance/movie/MovieDetailSteps.java
  be/src/test/resources/data_mainTest.sql
  fe/src/components/MovieDetailPage.jsx
  fe/src/components/MyPage.jsx
Labels: For: Api, For: View, Type: Feature

#98 Feat(be) #95. 영화 검색 api 구현, 테스트 완료
  be/src/main/java/movlit/be/common/config/SecurityConfig.java
  be/src/main/java/movlit/be/movie/application/service/MovieMainSearchService.java
  be/src/main/java/movlit/be/movie/domain/document/MovieCrewForDocument.java
  be/src/main/java/movlit/be/movie/domain/document/MovieDocument.java
  be/src/main/java/movlit/be/movie/domain/document/MovieGenreForDocument.java
  be/src/main/java/movlit/be/movie/domain/document/MovieTagForDocument.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieSearchRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  be/src/main/java/movlit/be/movie/presentation/MovieMainSearchController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieDocumentResponseDto.java
  be/src/main/resources/mappings/movie-mapping.json
  be/src/main/resources/mappings/movie-setting.json
  be/src/test/java/movlit/be/acceptance/movie/MovieSearchAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie/MovieSearchSteps.java
Labels: For: Api, For: View, Type: Feature

#105 Fe/feat/#104 movie search view
  be/src/main/java/movlit/be/movie/application/service/MovieMainSearchService.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  fe/src/App.css
  fe/src/App.jsx
  fe/src/main.jsx
  fe/src/pages/Home.css
  fe/src/pages/MovieCarousel.jsx
  fe/src/pages/MovieSearchDetailPage.jsx
  fe/src/pages/SearchDetailPage.css
  fe/src/pages/SearchPage.css
  fe/src/pages/SearchPage.jsx
Labels: For: View, Type: Feature

#117 [be] 영화 상세 페이지 리팩토링
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/common/config/AppConfig.java
  be/src/main/java/movlit/be/member/application/converter/MemberConverter.java
  be/src/main/java/movlit/be/movie/application/converter/detail/MovieConvertor.java
  be/src/main/java/movlit/be/movie/application/service/MovieCommentReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieCrewReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailWriteService.java
  be/src/main/java/movlit/be/movie/application/service/MovieGenreReadService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieCommentRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieCommentRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieCommentJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieDetailWriteController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCommentResponse.java
  be/src/main/java/movlit/be/movie_comment_heart/application/service/MovieCommentLikeReadService.java
  be/src/main/java/movlit/be/movie_comment_heart/application/service/MovieCommentLikeWriteService.java
  be/src/main/java/movlit/be/movie_comment_heart/application/service/dto/response/MovieCommentLikeSavedResponse.java
  be/src/main/java/movlit/be/movie_comment_heart/domain/repository/MovieCommentLikeRepository.java
  be/src/main/java/movlit/be/movie_comment_heart/infra/MovieCommentLikeRepositoryImpl.java
  be/src/main/java/movlit/be/movie_comment_heart/presentation/MovieCommentLikeController.java
  be/src/main/java/movlit/be/movie_comment_heart/presentation/dto/response/MovieCommentLikeResponse.java
  be/src/main/java/movlit/be/movie_comment_heart_count/application/service/MovieCommentLikeCountReadService.java
  be/src/main/java/movlit/be/movie_comment_heart_count/application/service/MovieCommentLikeCountWriteService.java
  be/src/main/java/movlit/be/movie_comment_heart_count/domain/MovieCommentLikeCountRepository.java
  be/src/main/java/movlit/be/movie_comment_heart_count/infra/persistence/MovieCommentLikeCountRepositoryImpl.java
  be/src/main/java/movlit/be/movie_comment_heart_count/infra/persistence/jpa/MovieCommentLikeCountJpaRepository.java
  be/src/test/java/movlit/be/acceptance/movie_comment/MovieCommentSteps.java
  be/src/test/java/movlit/be/acceptance/movie_comment_like/MovieCommentLikeAcceptanceTest.java
  be/src/test/java/movlit/be/acceptance/movie_comment_like/MovieCommentLikeSteps.java
  be/src/test/java/movlit/be/movie_comment_heart_count/application/service/MovieCommentLikeCountWriteServiceTest.java
Labels: For: Api, Type: Feature, Type: Refactor, Type: Fix

#118 [be] #115 movie main api refactoring
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/movlit/be/member/application/service/MemberGenreService.java
  be/src/main/java/movlit/be/movie/application/service/MovieCrewReadServiceMyk.java
  be/src/main/java/movlit/be/movie/application/service/MovieDetailSearchService.java
  be/src/main/java/movlit/be/movie/application/service/MovieReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieSearchService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieCrewRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieRepository.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieSearchRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieCrewRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieSearchRepositoryImpl.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieJpaRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/jpa/MovieRCrewJpaRepository.java
  be/src/main/java/movlit/be/movie/presentation/MovieReadController.java
  be/src/main/java/movlit/be/movie/presentation/MovieSearchController.java
  be/src/main/java/movlit/be/movie/presentation/dto/response/MovieCrewResponseDto.java
  be/src/main/java/movlit/be/movie_heart/application/service/MovieHeartService.java
  be/src/main/java/movlit/be/movie_heart/domain/repository/MovieHeartRepository.java
  be/src/main/java/movlit/be/movie_heart/infra/MovieHeartRepositoryImpl.java
Labels: For: Api, Type: Refactor

#119 Refactor(be) Movie Main 페이지 1차 리펙토링 안쓰는 메서드 추가 삭제
  be/src/main/java/movlit/be/movie/application/service/MovieReadService.java
  be/src/main/java/movlit/be/movie/application/service/MovieSearchService.java
  be/src/main/java/movlit/be/movie/domain/repository/MovieRepository.java
  be/src/main/java/movlit/be/movie/infra/persistence/MovieRepositoryImpl.java
Labels: For: Api, Type: Refactor
